config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'home#index'
  resources :cuisines, only: [:new, :show, :create]
  resources :recipes, only: [:new, :show, :create, :edit, :update, :destroy] do
    collection do
      get 'search'
      get 'list'
      get 'mine'
      get 'my_favorites'
    end
    member do
      post 'favorite'
      delete 'destroy_favorite'
      post 'share'
    end
  end

  resources :recipe_types, only: [:new, :show, :create]

end

app/models/recipe.rb
class Recipe < ApplicationRecord
  attr_accessor :recipe_cover
  belongs_to :cuisine
  belongs_to :recipe_type
  belongs_to :user
  validates(:title,
            :recipe_type,
            :difficulty,
            :cook_time,
            :ingredients,
            :method,
            :cuisine,
            presence: true)

  has_many :favorites, dependent: :destroy

  has_attached_file(:recipe_cover,
                    styles: { large: '500x500#',
                              medium: '300x300#',
                              thumb: '120x100#' },
                    default_url: '/assets/thumb/sem-foto.gif')
  validates_attachment_content_type(:recipe_cover,
                                    content_type: %r{/\Aimage\/.*\z/})

  def user_owner?(user)
    self.user == user
  end
end

app/models/recipe_type.rb
class RecipeType < ApplicationRecord
  has_many :recipes, dependent: :destroy
  validates :name, presence: true
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  before_action :authenticate_user!, only: %i[new edit destroy update mine]
  before_action :set_recipe, only: %i[show edit update
                                      favorite destroy_favorite share]
  before_action :options_for_select,
                only: %i[show new create edit update
                         search my_favorites list mine]

  def show
    id = params[:id]
    @favorite = Favorite.new
    @recipe = Recipe.find id
    @cuisine = Cuisine.find(@recipe.cuisine_id).name
  end

  def new
    @recipe = Recipe.new
  end

  def create
    @recipe = Recipe.new(recipe_params)
    @recipe.user = current_user

    if @recipe.save
      @cuisine = Cuisine.find(@recipe.cuisine_id).name
      redirect_to @recipe, notice: 'Receita Cadastrada com sucesso!'
    else
      flash.now[:alert] = 'Você deve informar todos os dados da receita'
      render 'new'

    end
  end

  def edit
    @recipe = Recipe.find params[:id]
    if @recipe.user_owner?(current_user)
      return
    else
      redirect_to root_path, notice: 'Você não tem permissão para isso!'
    end
  end

  def update
    @recipe = Recipe.find params[:id]
    if @recipe.user_owner?(current_user)
      if @recipe.update(recipe_params)
        redirect_to @recipe, notice: 'Receita atualizada com sucesso!'
      else
        flash.now[:alert] = 'Você deve informar todos os dados da receita'
        render 'edit'
      end
    else
      redirect_to root_path, notice: 'Você não tem permissão para isso!'
    end
  end

  def destroy
    @recipe = Recipe.find params[:id]
    if @recipe.destroy
      redirect_to root_path
    else
      flash.now[:notice] = 'Esta receita não pode ser excluída'
      render 'show'
    end
  end

  def search
    @query = params[:query]
    @results = Recipe.where('title LIKE ? OR ingredients LIKE ?',
                            @query, @query)
  end

  def my_favorites
    user_favorites
  end

  def list
    options_for_select
  end

  def mine
    user_recipes
  end

  def favorite
    user = params[:user]
    recipe = params[:recipe]
    @favorite = User.find(user).favorites.new(recipe_id: recipe)
    return unless @favorite.save
    redirect_to recipe_path(recipe), notice: 'Receita adicionada aos favoritos!'
  end

  def destroy_favorite
    recipe = params[:recipe]
    @favorite = Favorite.find_by user_id: current_user, recipe_id: params[:id]
    if @favorite.destroy
      redirect_to recipe_path(recipe),
                  notice: 'Receita removida dos favoritos.'
    else
      redirect_to recipe_path(recipe),
                  notice: 'Receita não pode ser removida dos favoritos'
    end
  end

  def share
    email = params[:email]
    msg = params[:message]

    UserMailer.recommend_email(email, msg,
                               @recipe.id).deliver_now

    flash[:notice] = "Receita enviada para #{email}"
    redirect_to @recipe
  end
end

private

def options_for_select
  @recipe_all = Recipe.all
  @recipe_type_all = RecipeType.all
  @cuisine_all = Cuisine.all
end

def user_favorites
  @favorites = []
  fav = Favorite.where(user: current_user)
  fav.each do |f|
    @favorites << f.recipe
  end
end

def user_recipes
  @my_recipes = Recipe.where(user: current_user)
end

def recipe_params
  params.require(:recipe).permit(:title,
                                 :cuisine_id,
                                 :recipe_type_id,
                                 :difficulty,
                                 :cook_time,
                                 :ingredients,
                                 :method,
                                 :recipe_cover,
                                 :featured)
end

def set_recipe
  @recipe = Recipe.find(params[:id])
end

app/views/recipes/_form.html.erb
<div id="menu">
    <%= render 'layouts/navbar' %>
</div> 
    
 <div class="main">
   
      <% if @recipe.errors.any? %>
      <div class="error-alert">
          <div class="alert alert-warning alert-dismissable">
            <p><%= flash[:alert] %></p>
        </div>
      </div>
      <% end %>

    <%= form_for @recipe, html: {class: 'basic-grey', multipart: true} do |f| %>
      
      <% if @recipe.id.nil? %>
        <h1>Nova Receita</h1>
      <% else %>
        <h1>Editando <%= @recipe.title %></h1>
      <% end %> 
      
      <div class="check_box">
        <%= f.label :featured, 'Destaque' %>
        <%= f.check_box :featured %>
      </div>
      
      <div class="field">
        <%= f.label :title, 'Título' %>
        <%= f.text_field :title %>
      </div>
      
      <div class="field">
        <%= f.label :cuisine_id, 'Cozinha' %>
        <%= f.collection_select(:cuisine_id, @cuisine_all, :id, :name) %>
      </div>
      
      <div class="field">
        <%= f.label :recipe_type_id, 'Tipo da Receita' %>
        <%= f.collection_select(:recipe_type_id, @recipe_type_all, :id, :name) %>
      </div>
    
      <div class="field">
        <%= f.label :difficulty, 'Dificuldade' %>
        <%= f.text_field :difficulty %>
      </div>
      
      <div class="field">
        <%= f.label :cook_time, 'Tempo de Preparo' %>
        <%= f.text_field :cook_time %>
      </div>
      
      <div class="field">
        <%= f.label :ingredients, 'Ingredientes' %>
        <%= f.text_field :ingredients %>
      </div>
      
      <div class="field">
        <%= f.label :method, 'Como Preparar' %>
        <%= f.text_field :method %>
      </div>
      
      <div>
        <%= f.label :recipe_cover, 'Foto da Receita' %>
        <%= f.file_field :recipe_cover %>  
      </div>
       <br>     
      <div> 
        <%= f.submit 'Enviar', class:'button' %>
      </div>
    <% end %>
  
</div>

app/views/recipes/edit.html.erb
<%= render 'form' %>

app/views/recipes/list.html.erb
  <div id="menu">
    <%= render 'layouts/navbar' %>
  </div>
  
<div class='basic-grey'>
  <h1>Todas as Receitas</h1>
  
<%= render partial: '/shared/recipe_list_grid', locals: {recipes:  @recipe_all} %>
  
</div>

app/views/recipes/mine.html.erb
<div id="menu">
  <%= render 'layouts/navbar' %>
</div> 

<div class="basic-grey">
  <h1>Minhas receitas</h1>
    <%= render partial: '/general_partials/recipe_list', locals: {recipes:  @my_recipes} %>
</div>

app/views/recipes/my_favorites.html.erb
<div id="menu">
  <%= render 'layouts/navbar' %>
</div> 

<div class="basic-grey">
    <% if flash[:notice] %>
    <div class="alert alert-success alert-dismissable">
      <a href="#" class="close" data-dismiss="alert" aria-label="close">×</a>
     <p><%= flash[:notice] %></p> 
    </div>
  <% end %>
    <%= render partial: '/shared/recipe_list', locals: {recipes:  @favorites} %>
</div>

app/views/recipes/new.html.erb
<%= form_for @receita do |f| %>
  <div>
    <%= f.label :title, 'Título' %>
    <%= f.text_field :title %>
  </div>
  
  <div>
    <%= f.label :recipe_type, 'Tipo da Receita' %>
    <%= f.text_field :recipe_type %>
  </div>
  
  <div>
    <%= f.label :cuisine, 'Cozinha' %>
    <%= f.select(:cuisine, @cuisine_options_for_select) %>

  </div>

  <div>
    <%= f.label :difficulty, 'Dificuldade' %>
    <%= f.text_field :difficulty %>
  </div>
  
  <div>
    <%= f.label :cook_time, 'Tempo de Preparo' %>
    <%= f.text_field :cook_time %>
  </div>
  
  <div>
    <%= f.label :ingredients, 'Ingredientes' %>
    <%= f.text_field :ingredients %>
  </div>
  
  <div>
    <%= f.label :method, 'Como Preparar' %>
    <%= f.text_field :method %>
  </div>
  
  <div> 
    <%= f.submit 'Enviar' %>
  </div>

<% end %>

app/views/recipes/search.html.erb
<div id="menu">
    <%= render 'layouts/navbar' %>
</div> 
    
<div class="main">  
   <h1><%="Resultado da busca por: #{@query}"%></h1>
   <% if @results.empty? %>
      <h2><%= "Nenhum resultado para: #{@query}" %></h2>
      
   <% else %>
      <% @results.each do |result| %>
         <h1><%= link_to result.title, recipe_path(result.id) %></h1>
         <li><%= result.recipe_type.name%></li>
         <li><%= result.cuisine.name%></li>
         <li><%= result.difficulty%></li>
         <li><%= result.cook_time%> minutos</li>
      <% end %>
   <% end %>
</div>
   

app/views/recipes/show.html.erb
<div id="menu">
    <%= render 'layouts/navbar' %>
</div> 
    
<div class="basic-grey">
  <% if flash[:notice] %>
  <div class="alert alert-success alert-dismissable">
    <a href="#" class="close" data-dismiss="alert" aria-label="close">×</a>
    <p><%= flash[:notice] %></p> 
    </div>
  <% end %>
  
  <div class='container'>
    <div class='row'>
      <div class='col-md-3'>
        <h1><%= @recipe.title %> <%= image_tag 'star.png' if @recipe.featured %> </h1>
        
        <p>Enviado por: <%= @recipe.user.email %></p>
        <h3>Detalhes</h3>
        <ul class= 'recipe-details'>
          <li><b>Tipo:</b> <%= @recipe.recipe_type.name%></li>
          <li><b>Cozinha:</b> <%= @recipe.cuisine.name%></li>
          <li><b>Dificuldade:</b> <%= @recipe.difficulty%></li>
          <li><b>Tempo:</b> <%= @recipe.cook_time %> minutos</li>
        </ul>
        
        <h3>Ingredientes</h3>
        <p><%= @recipe.ingredients %></p>

        
        <% if user_signed_in? && @recipe.user_owner?(current_user) %>
          <%= link_to 'Editar', edit_recipe_path %>
          <%= link_to 'Excluir', @recipe, method: :delete, data: { confirm: 'Tem certeza que deseja exclur esta receita?' }%>
        <% end %>
        <%= link_to 'Voltar', root_path %>
      </div>
      
      <div class='col-md-6'>
        <%= image_tag @recipe.recipe_cover.url(:large), class: 'img-responsive img-rounded' %>
        <div class='method'>
        <h3>Como Preparar</h3>
        <p><%= @recipe.method %></p>
        
        <div class='options'>
          <% if user_signed_in? %>
            <% if current_user.favorited?(@recipe)  %>
              <p><%= link_to 'Remover dos Favoritos', destroy_favorite_recipe_path(recipe: @recipe), method: :delete, class: 'glyphicon glyphicon-star' %></p>
            <% else %>
              <p><%= link_to 'Adicionar aos Favoritos', favorite_recipe_path(recipe: @recipe, user: current_user), method: :post, class: 'glyphicon glyphicon-star-empty' %> </p>
            <% end %>
          <% end %>
          
          <%= render '/recipes/partials/send_email' %>
        </div>
        
      </div>
    </div>
  </div>
</div>

      

      