config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'home#index'
  resources :cuisines, only: [:new, :show, :create]
  resources :recipes, only: [:new, :show, :create, :edit, :update, :destroy] do
    collection do
      get 'search'
      get 'list'
      get 'mine'
      get 'my_favorites'
    end
    member do
      post 'favorite'
      delete 'destroy_favorite'
      post 'share'
    end
  end

  resources :recipe_types, only: [:new, :show, :create]

end

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-inverse navbar-fixed-top">
    <div class="navbar-header">
  <li><%= link_to 'My Cookbook', root_path, class: 'navbar-brand' %></li>
  </div>
  <ul class="nav navbar-nav">
  <li class='active'><%= link_to 'Todas as Receitas', list_recipes_path%></li>
  <% if user_signed_in? %>
  <li><%= link_to 'Minhas Receitas', mine_recipes_path %></li>
    <li><%= link_to 'Favoritas', my_favorites_recipes_path %></li>
    <li><%= link_to "Olá, #{current_user.email}"%></li>
    <li><%= link_to 'Sair', destroy_user_session_path, method: :delete %></li>
    
  <% else %>
    <li><%= link_to 'Entrar', new_user_session_path %></li>
    <li><%= link_to 'Criar Conta', new_user_registration_path %></li>
  <% end %>
  
  <li id="search-box"><%= render 'layouts/search_form' %></li>
  </ul>
</nav>

<div class="sidenav">
  <%= render 'layouts/navbar_side' %>
</div>

app/views/layouts/_navbar_side.html.erb
       <h2>Tipo</h2>
       <% @recipe_type_all.each do |recipe_type| %>
         <h1><%= link_to recipe_type.name, recipe_type %></h1>
       <% end %>
       <h2>Cozinha</h2>
       <% @cuisine_all.each do |cuisine| %>
        <h1><%= link_to cuisine.name, cuisine %></h1>
       <% end %>
       <% if user_signed_in? %>
       <%= link_to 'Enviar uma receita', new_recipe_path, class:"btn btn-danger navbar-btn" %>
       <% end %>

app/views/layouts/_search_form.html.erb
<%= form_tag(search_recipes_path, method: "get", class:"navbar-form navbar-left") do %>
    <%= label_tag(:query, "Busca", class: 'hidden') %>
    <%= text_field_tag :query, "Pesquisar Receita", class: "form-control" %>
    <%= submit_tag "Buscar", class:"btn btn-default"%>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>My Cookbook</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <%= yield %>
  </body>
</html>